# Generated by Django 3.2.13 on 2022-08-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milan_morningsingledigit',
            name='digit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='milan_morningsingledigit',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
