# Generated by Django 3.2.13 on 2022-08-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0003_milan_morningdoublepana_milan_morningfullsangam_milan_morninghalfsangam_milan_morningjodidigit_milan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milan_morningfullsangam',
            old_name='close_pana_pana',
            new_name='close_pana',
        ),
    ]
