# Generated by Django 3.2.13 on 2022-08-27 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satta_king', '0005_welcome_morningdoublepana_welcome_morningfullsangam_welcome_morninghalfsangam_welcome_morningjodidig'),
    ]

    operations = [
        migrations.CreateModel(
            name='POINTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
