# Generated by Django 4.1 on 2022-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0015_dailybazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybazar',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
