# Generated by Django 4.1 on 2022-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0018_alter_everyhour_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaliDisawar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Disawar', 'Disawar'), ('Faridabaad', 'Faridabaad'), ('Gaziabaad', 'Gaziabaad'), ('Gali', 'Gali')], max_length=100)),
                ('Number', models.CharField(max_length=2)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
