# Generated by Django 4.1 on 2022-09-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0020_dailytime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EveryHour',
            new_name='Starline',
        ),
    ]
