# Generated by Django 4.1 on 2022-09-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0021_rename_everyhour_starline'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaliDisawarTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Disawar', 'Disawar'), ('Faridabaad', 'Faridabaad'), ('Gaziabaad', 'Gaziabaad'), ('Gali', 'Gali')], max_length=100)),
                ('Open_Time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StarlineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('01 PM', '01 PM'), ('02 PM', '02 PM'), ('03 PM', '03 PM'), ('04 PM', '04 PM'), ('05 PM', '05 PM'), ('06 PM', '06 PM'), ('07 PM', '07 PM'), ('08 PM', '08 PM'), ('09 PM', '09 PM'), ('10 PM', '10 PM')], max_length=100)),
                ('Open_Time', models.CharField(max_length=4)),
            ],
        ),
    ]
