# Generated by Django 4.1 on 2022-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satta_king', '0023_alter_dailytime_close_time_alter_dailytime_opne_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galidisawartime',
            name='Close_Time',
            field=models.CharField(default='10', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starlinetime',
            name='Close_Time',
            field=models.CharField(default='10', max_length=8),
            preserve_default=False,
        ),
    ]
