from django.contrib import admin
from satta_king.models import *

# Register your models here.
admin.site.register(POINTS)
admin.site.register(MANAGEBANK)
admin.site.register(Images)
admin.site.register(Profile)

admin.site.register(Milan_MorningSingleDigit)
admin.site.register(Milan_MorningJodiDigit)
admin.site.register(Milan_MorningSinglePana)
admin.site.register(Milan_MorningDoublePana)
admin.site.register(Milan_MorningTriplePana)
admin.site.register(Milan_MorningHalfSangam)
admin.site.register(Milan_MorningFullSangam)

admin.site.register(Welcome_MorningSingleDigit)
admin.site.register(Welcome_MorningJodiDigit)
admin.site.register(Welcome_MorningSinglePana)
admin.site.register(Welcome_MorningDoublePana)
admin.site.register(Welcome_MorningTriplePana)
admin.site.register(Welcome_MorningHalfSangam)
admin.site.register(Welcome_MorningFullSangam)

admin.site.register(Kalyan_MorningSingleDigit)
admin.site.register(Kalyan_MorningJodiDigit)
admin.site.register(Kalyan_MorningSinglePana)
admin.site.register(Kalyan_MorningDoublePana)
admin.site.register(Kalyan_MorningTriplePana)
admin.site.register(Kalyan_MorningHalfSangam)
admin.site.register(Kalyan_MorningFullSangam)

admin.site.register(Madhur_MorningSingleDigit)
admin.site.register(Madhur_MorningJodiDigit)
admin.site.register(Madhur_MorningSinglePana)
admin.site.register(Madhur_MorningDoublePana)
admin.site.register(Madhur_MorningTriplePana)
admin.site.register(Madhur_MorningHalfSangam)
admin.site.register(Madhur_MorningFullSangam)

admin.site.register(SrideviSingleDigit)
admin.site.register(SrideviJodiDigit)
admin.site.register(SrideviSinglePana)
admin.site.register(SrideviDoublePana)
admin.site.register(SrideviTriplePana)
admin.site.register(SrideviHalfSangam)
admin.site.register(SrideviFullSangam)

admin.site.register(Time_Bazar_SingleDigit)
admin.site.register(Time_Bazar_JodiDigit)
admin.site.register(Time_Bazar_SinglePana)
admin.site.register(Time_Bazar_DoublePana)
admin.site.register(Time_Bazar_TriplePana)
admin.site.register(Time_Bazar_HalfSangam)
admin.site.register(Time_Bazar_FullSangam)

admin.site.register(Madhur_Day_SingleDigit)
admin.site.register(Madhur_Day_JodiDigit)
admin.site.register(Madhur_Day_SinglePana)
admin.site.register(Madhur_Day_DoublePana)
admin.site.register(Madhur_Day_TriplePana)
admin.site.register(Madhur_Day_HalfSangam)
admin.site.register(Madhur_Day_FullSangam)

admin.site.register(New_Kalyan_SingleDigit)
admin.site.register(New_Kalyan_JodiDigit)
admin.site.register(New_Kalyan_SinglePana)
admin.site.register(New_Kalyan_DoublePana)
admin.site.register(New_Kalyan_TriplePana)
admin.site.register(New_Kalyan_HalfSangam)
admin.site.register(New_Kalyan_FullSangam)

admin.site.register(Milan_Day_SingleDigit)
admin.site.register(Milan_Day_JodiDigit)
admin.site.register(Milan_Day_SinglePana)
admin.site.register(Milan_Day_DoublePana)
admin.site.register(Milan_Day_TriplePana)
admin.site.register(Milan_Day_HalfSangam)
admin.site.register(Milan_Day_FullSangam)

admin.site.register(Rajdhani_Day_SingleDigit)
admin.site.register(Rajdhani_Day_JodiDigit)
admin.site.register(Rajdhani_Day_SinglePana)
admin.site.register(Rajdhani_Day_DoublePana)
admin.site.register(Rajdhani_Day_TriplePana)
admin.site.register(Rajdhani_Day_HalfSangam)
admin.site.register(Rajdhani_Day_FullSangam)

admin.site.register(Supreme_Day_SingleDigit)
admin.site.register(Supreme_Day_JodiDigit)
admin.site.register(Supreme_Day_SinglePana)
admin.site.register(Supreme_Day_DoublePana)
admin.site.register(Supreme_Day_TriplePana)
admin.site.register(Supreme_Day_HalfSangam)
admin.site.register(Supreme_Day_FullSangam)

admin.site.register(Kalyan_SingleDigit)
admin.site.register(Kalyan_JodiDigit)
admin.site.register(Kalyan_SinglePana)
admin.site.register(Kalyan_DoublePana)
admin.site.register(Kalyan_TriplePana)
admin.site.register(Kalyan_HalfSangam)
admin.site.register(Kalyan_FullSangam)

admin.site.register(Sridevi_Night_SingleDigit)
admin.site.register(Sridevi_Night_JodiDigit)
admin.site.register(Sridevi_Night_SinglePana)
admin.site.register(Sridevi_Night_DoublePana)
admin.site.register(Sridevi_Night_TriplePana)
admin.site.register(Sridevi_Night_HalfSangam)
admin.site.register(Sridevi_Night_FullSangam)

admin.site.register(Madhur_Night_SingleDigit)
admin.site.register(Madhur_Night_JodiDigit)
admin.site.register(Madhur_Night_SinglePana)
admin.site.register(Madhur_Night_DoublePana)
admin.site.register(Madhur_Night_TriplePana)
admin.site.register(Madhur_Night_HalfSangam)
admin.site.register(Madhur_Night_FullSangam)

admin.site.register(New_Main_Mumbai_SingleDigit)
admin.site.register(New_Main_Mumbai_JodiDigit)
admin.site.register(New_Main_Mumbai_SinglePana)
admin.site.register(New_Main_Mumbai_DoublePana)
admin.site.register(New_Main_Mumbai_TriplePana)
admin.site.register(New_Main_Mumbai_HalfSangam)
admin.site.register(New_Main_Mumbai_FullSangam)

admin.site.register(Supreme_Night_SingleDigit)
admin.site.register(Supreme_Night_JodiDigit)
admin.site.register(Supreme_Night_SinglePana)
admin.site.register(Supreme_Night_DoublePana)
admin.site.register(Supreme_Night_TriplePana)
admin.site.register(Supreme_Night_HalfSangam)
admin.site.register(Supreme_Night_FullSangam)

admin.site.register(Milan_Night_SingleDigit)
admin.site.register(Milan_Night_JodiDigit)
admin.site.register(Milan_Night_SinglePana)
admin.site.register(Milan_Night_DoublePana)
admin.site.register(Milan_Night_TriplePana)
admin.site.register(Milan_Night_HalfSangam)
admin.site.register(Milan_Night_FullSangam)

admin.site.register(Kalyan_Night_SingleDigit)
admin.site.register(Kalyan_Night_JodiDigit)
admin.site.register(Kalyan_Night_SinglePana)
admin.site.register(Kalyan_Night_DoublePana)
admin.site.register(Kalyan_Night_TriplePana)
admin.site.register(Kalyan_Night_HalfSangam)
admin.site.register(Kalyan_Night_FullSangam)

admin.site.register(Rajdhani_Night_SingleDigit)
admin.site.register(Rajdhani_Night_JodiDigit)
admin.site.register(Rajdhani_Night_SinglePana)
admin.site.register(Rajdhani_Night_DoublePana)
admin.site.register(Rajdhani_Night_TriplePana)
admin.site.register(Rajdhani_Night_HalfSangam)
admin.site.register(Rajdhani_Night_FullSangam)

admin.site.register(Main_Bazar_SingleDigit)
admin.site.register(Main_Bazar_JodiDigit)
admin.site.register(Main_Bazar_SinglePana)
admin.site.register(Main_Bazar_DoublePana)
admin.site.register(Main_Bazar_TriplePana)
admin.site.register(Main_Bazar_HalfSangam)
admin.site.register(Main_Bazar_FullSangam)